name: 04 _ Using actions
on: push
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            # 0 checkout the code from the repository

            - name: Checkout code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls

        
        # 1 install dependencies of react app
         # 2  execute automated tests 