name: 05-01- Event Filters and activity types

on:

    pull_request:
        branches:
            - main
        types: 
            - opened
            - synchronize

            

jobs:
    echo-05:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is opened/synchronize And base branch is main"