name: 11 _ working with inputs

on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: Skip deployment and only print build output 
                default: false
            target:
                type: environment
                required: true
                description: wich environnement the workflow will target 

            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: Release from wich to build  & deploy

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "building from tag  ${{inputs.tag}}"
    deploy:
        runs-on: ubuntu-latest
        if: ${{!inputs.dry-run}}
        environment: ${{inputs.target}}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{inputs.target}}"
