name: 15_working_with_Matrices

on:
    workflow_dispatch:
    push:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }} - Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Debug information
        run: |
         node -v
         npm -v
         npm list
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Perform some tests
        run: echo "Running tests on OS ${{ matrix.os }} and Node.js ${{ matrix.node-version }}"
