name: 18.1 _ Reusable workflows _ reusable definition

on:
    workflow_call:
        inputs:
            target-directory:
                type: string
                required: true
        outputs:
            build-status:
                description: The status  of the build process
                value: ${{jobs.deploy.outputs.build-status}}
            url:
                description: url of the deployed version
                value: ${{jobs.deploy.outputs.url}}
jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build.outputs.build-status}}
            url: ${{steps.deploy.outputs.url}}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Build
              id: build
              run: |
                echo "Building using directory :${{inputs.target-directory}}"
                echo "build-status=sucess" >> "$GITHUB_OUTPUT"
            - name: Deploy
              id: deploy
              run: |
                echo "deploying artifacts.."
                echo "url = https://www.google.com" >> "$GITHUB_OUTPUT"

