name: 18.2 _ Reusable workflows 

on: 
    workflow_dispatch:
jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflows.yaml
        with:
            target-directory: dummy-dir
    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Print outputs
              run: |
                echo "build status: ${{needs.deploy.outputs.build-status}}"
                echo "Url= ${{needs.deploy.outputs.url}}"